image: maven:latest

stages:
  - build
  - test

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

build:
  stage: build
  tags:
    - ugrad
  script:
    - mvn clean compile

test:
  stage: test
  tags:
    - ugrad
  script:
    - echo test_stage




