image: maven:latest

stages:
  - build
  - test
  - code_quality
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

build:
  stage: build
  tags:
    - ugrad
  script:
    - mvn clean compile

test:
  stage: test
  tags:
    - ugrad
  script:
    - echo test_stage

code_quality:
  stage: code_quality
  tags:
    - ugrad
  variables:
    UPLOAD_QUALITY_REPORT: 'curl -X PUT -H "Authorization: Token $QSCORED_API_KEY" -H "repository-link: $CI_PROJECT_URL"+ -H "dhsoni2510@gmail.com" -H "Content-Type: multipart/form-data" --url "https://qscored.com/api/upload/file.xml?is_open_access=off&version=$CI_PIPELINE_IID&project_name=bethedonor-demo" -F "file=@Designite_output/DesigniteAnalysis.xml"'

  script:
    - wget -O DesigniteJava.jar https://www.dropbox.com/s/hrfuiesdb9o6cg5/DesigniteJava.jar?dl=1
    - java -jar DesigniteJava.jar -ci -repo $CI_PROJECT_PATH -pat $PAT -host "https://git.cs.dal.ca/"
    - eval "$UPLOAD_QUALITY_REPORT"

  only:
    - test


deploy_dev:
  stage: deploy
  image: ruby:latest
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=bethedonor-dev --api-key=$HEROKU_API_KEY
  environment:
    name: dev
    url: https://bethedonor-dev.herokuapp.com
  only:
    - master

