image: maven:latest

stages:
  - build
  - test
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

build:
  stage: build
  tags:
    - ugrad
  script:
    - mvn clean compile

test:
  stage: test
  tags:
    - ugrad
  script:
    - echo test_stage

deploy_dev:
  stage: deploy
  image: ruby:latest
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=bethedonor-dev --api-key=$HEROKU_API_KEY
  environment:
    name: dev
    url: https://bethedonor-dev.herokuapp.com
  only:
    - master
