server:

  error:
    include:message: always
    include-binding-errors: always


spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://db-5308.cs.dal.ca:3306/CSCI5308_23_TEST?createDatabaseIfNotExist=true
    username: CSCI5308_23_TEST_USER
    password: Phubaigh6li1Aef1


  jpa:
    hibernate:
      ddl-auto: update
      connection:
        release_mode: after_statement
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        formate_sql: true
    show-sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: dhsoni2510@gmail.com
    password: rjrgzkiwukrgurql

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  jackson:
    serialization:
      fail-on-empty-beans: false

STRIPE_SECRET_KEY : sk_test_51Kk3ylF7Q5o75Cq7iWlkSvUFxseuFv8Pn9X05wRWgd32NR1HqXGMnpPXriKHIldDDplIMf5kpkeSsAI1v0NujML50076CQe4Zn
STRIPE_PUBLIC_KEY : pk_test_51Kk3ylF7Q5o75Cq78Bl0G00iWpJ1ITQcF5kFImeeIosv1OUAwbitTabCMJC2Yb6SD7NDkewC3XDu4mLqKR1vuBnd00HAgGzZ8f
